-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 05:47:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`edital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edital` (
  `id_edital` INT NOT NULL AUTO_INCREMENT,
  `numero_edital` VARCHAR(45) NOT NULL,
  `data_publicado` DATETIME NOT NULL,
  `url_pdf` VARCHAR(100) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_edital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleicao` (
  `id_eleicao` INT NOT NULL AUTO_INCREMENT,
  `id_edital` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `total_participantes` INT NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `cont_branco` INT NULL,
  `cont_nulo` INT NULL,
  `cont_faltante` INT NULL,
  PRIMARY KEY (`id_eleicao`),
  INDEX `fk_eleicao_edital_idx` (`id_edital` ASC),
  CONSTRAINT `fk_eleicao_edital`
    FOREIGN KEY (`id_edital`)
    REFERENCES `mydb`.`edital` (`id_edital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sistema` (
  `id_sistema` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante` (
  `id_participante` INT NOT NULL AUTO_INCREMENT,
  `cargo_id_cargo` INT NOT NULL,
  `cpf` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id_participante`),
  INDEX `fk_participante_cargo1_idx` (`cargo_id_cargo` ASC),
  CONSTRAINT `fk_participante_cargo1`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `mydb`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidato` (
  `id_candidato` INT NOT NULL AUTO_INCREMENT,
  `id_eleicao` INT NOT NULL,
  `id_edital` INT NOT NULL,
  `id_participante` INT NOT NULL,
  `status` VARCHAR(11) NOT NULL,
  `votos` INT NULL,
  INDEX `fk_candidato_eleicao1_idx` (`id_eleicao` ASC),
  INDEX `fk_candidato_edital1_idx` (`id_edital` ASC),
  INDEX `fk_candidato_participante1_idx` (`id_participante` ASC),
  PRIMARY KEY (`id_candidato`),
  CONSTRAINT `fk_candidato_eleicao1`
    FOREIGN KEY (`id_eleicao`)
    REFERENCES `mydb`.`eleicao` (`id_eleicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_edital1`
    FOREIGN KEY (`id_edital`)
    REFERENCES `mydb`.`edital` (`id_edital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_participante1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confirma_voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confirma_voto` (
  `id_confirma` INT NOT NULL AUTO_INCREMENT,
  `id_participante` INT NOT NULL,
  `id_eleicao` INT NOT NULL,
  `votou` TINYINT NOT NULL,
  INDEX `fk_confirma_voto_participante1_idx` (`id_participante` ASC),
  INDEX `fk_confirma_voto_eleicao1_idx` (`id_eleicao` ASC),
  PRIMARY KEY (`id_confirma`),
  CONSTRAINT `fk_confirma_voto_participante1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_confirma_voto_eleicao1`
    FOREIGN KEY (`id_eleicao`)
    REFERENCES `mydb`.`eleicao` (`id_eleicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
